# One index per arm, so the licence day's RolloverSummary breaks down by arm
# without any attribution guesswork. tenx_dml holds the compact arm's template
# dictionary and the app's own tenx_dml_pure events, both of which a deployment
# pays licence for and a file ratio never counts.

[tenx_base]
homePath   = $SPLUNK_DB/tenx_base/db
coldPath   = $SPLUNK_DB/tenx_base/colddb
thawedPath = $SPLUNK_DB/tenx_base/thaweddb

[tenx_enc]
homePath   = $SPLUNK_DB/tenx_enc/db
coldPath   = $SPLUNK_DB/tenx_enc/colddb
thawedPath = $SPLUNK_DB/tenx_enc/thaweddb

[tenx_dml]
homePath   = $SPLUNK_DB/tenx_dml/db
coldPath   = $SPLUNK_DB/tenx_dml/colddb
thawedPath = $SPLUNK_DB/tenx_dml/thaweddb
