# The forwarder's default 256 KBps thruput limit would stretch this run over
# half an hour of wall clock for no measurement reason. It shapes when bytes
# arrive, never how many, and the licence meter counts what arrives.
[thruput]
maxKBps = 0
