# Overrides the app's default dest_dml_index of "main". The app re-indexes each
# template a second time, as a searchable tenx_dml_pure event, when its Consume
# KV alert fills the KV store. That is licence-metered volume the compact arm
# causes, so it is pointed at the compact arm's own index rather than left in
# main where the arm would not be charged for it.
[config]
dest_dml_index = tenx_dml
